## Basic Configuration
baseurl = "https://example.com/"
languageCode = "es"

title = "Jerónimo Aranda"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Jerónimo Aranda"
    title = "Jerónimo Aranda"
    # description = "..."
    authorimage = "/img/jeronimo-aranda-barois.jpg"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    copyright = ""
    license = ""
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = false

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "https://github.com/jeroaranda"
    instagram = ""
    xing = ""
    linkedin = ""
    twitter = "https://twitter.com/jeroaranda"
    facebook = ""
    stackoverflow = ""
    telegram = ""
    email = "jeroaranda@gmail.com"
    # gravatar = ""

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Visualizations"
    identifier = "visualizations"
    weight = 150
    url = "/visualizations/"
[[menu.main]]
    name = "Portfolio"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
[[menu.main]]
    name = "About me"
    identifier = "about"
    weight = 300
    url = "/about/"
